version: 2

jobs:
  unit-test:
    docker:
      - image: haskell:8.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cabal-cache-{{ arch }}-{{ checksum "hscli.cabal" }}
      - run:
          name: Update cabal
          command: cabal v2-update
      - run:
          name: Build
          command: cabal v2-build --enable-tests
      - run:
          name: Run tests
          command: cabal v2-test --enable-tests
      - save_cache:
          key: cabal-cache-{{ arch }}-{{ checksum "hscli.cabal" }}
          paths:
            - "~/.cabal/store"
workflows:
  version: 2
  tests:
    jobs:
      - unit-test
