version: 2

jobs:
  unit-test:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: cabal-install test

workflows:
  version: 2
  tests:
    jobs:
      - unit-test
